/**
 * AI-Assisted Question Generator for Quizzi
 *
 * Generates 1,000 questions across 5 categories:
 * - General Knowledge
 * - Geography
 * - Science
 * - Pop Culture
 * - Sports
 *
 * Distribution per category (200 each):
 * - 80 easy
 * - 80 medium
 * - 40 hard
 */

interface QuestionTemplate {
  category: string;
  difficulty: string;
  questionText: string;
  correctAnswer: string;
  wrongAnswer1: string;
  wrongAnswer2: string;
  wrongAnswer3: string;
}

/**
 * GENERAL KNOWLEDGE QUESTIONS (200 total)
 */
const GENERAL_KNOWLEDGE_QUESTIONS: QuestionTemplate[] = [
  // EASY (80)
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many days are in a leap year?', correctAnswer: '366', wrongAnswer1: '365', wrongAnswer2: '364', wrongAnswer3: '367' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of France?', correctAnswer: 'Paris', wrongAnswer1: 'London', wrongAnswer2: 'Berlin', wrongAnswer3: 'Madrid' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many continents are there?', correctAnswer: '7', wrongAnswer1: '5', wrongAnswer2: '6', wrongAnswer3: '8' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What color is a ruby?', correctAnswer: 'Red', wrongAnswer1: 'Blue', wrongAnswer2: 'Green', wrongAnswer3: 'Purple' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many sides does a triangle have?', correctAnswer: '3', wrongAnswer1: '4', wrongAnswer2: '5', wrongAnswer3: '6' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the largest ocean on Earth?', correctAnswer: 'Pacific', wrongAnswer1: 'Atlantic', wrongAnswer2: 'Indian', wrongAnswer3: 'Arctic' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many hours in a day?', correctAnswer: '24', wrongAnswer1: '12', wrongAnswer2: '48', wrongAnswer3: '36' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is H2O commonly known as?', correctAnswer: 'Water', wrongAnswer1: 'Oxygen', wrongAnswer2: 'Hydrogen', wrongAnswer3: 'Carbon dioxide' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many legs does a spider have?', correctAnswer: '8', wrongAnswer1: '6', wrongAnswer2: '10', wrongAnswer3: '4' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the freezing point of water in Celsius?', correctAnswer: '0°C', wrongAnswer1: '32°C', wrongAnswer2: '100°C', wrongAnswer3: '-32°C' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many colors in a rainbow?', correctAnswer: '7', wrongAnswer1: '5', wrongAnswer2: '6', wrongAnswer3: '8' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the tallest mammal?', correctAnswer: 'Giraffe', wrongAnswer1: 'Elephant', wrongAnswer2: 'Camel', wrongAnswer3: 'Horse' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What do bees produce?', correctAnswer: 'Honey', wrongAnswer1: 'Milk', wrongAnswer2: 'Silk', wrongAnswer3: 'Wax only' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many sides does a hexagon have?', correctAnswer: '6', wrongAnswer1: '5', wrongAnswer2: '7', wrongAnswer3: '8' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of Italy?', correctAnswer: 'Rome', wrongAnswer1: 'Venice', wrongAnswer2: 'Milan', wrongAnswer3: 'Florence' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What gas do plants absorb from the atmosphere?', correctAnswer: 'Carbon dioxide', wrongAnswer1: 'Oxygen', wrongAnswer2: 'Nitrogen', wrongAnswer3: 'Hydrogen' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many months have 31 days?', correctAnswer: '7', wrongAnswer1: '6', wrongAnswer2: '8', wrongAnswer3: '5' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the largest planet in our solar system?', correctAnswer: 'Jupiter', wrongAnswer1: 'Saturn', wrongAnswer2: 'Neptune', wrongAnswer3: 'Earth' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many weeks in a year?', correctAnswer: '52', wrongAnswer1: '50', wrongAnswer2: '48', wrongAnswer3: '56' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the smallest prime number?', correctAnswer: '2', wrongAnswer1: '1', wrongAnswer2: '3', wrongAnswer3: '0' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of Spain?', correctAnswer: 'Madrid', wrongAnswer1: 'Barcelona', wrongAnswer2: 'Seville', wrongAnswer3: 'Valencia' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many strings does a standard guitar have?', correctAnswer: '6', wrongAnswer1: '5', wrongAnswer2: '7', wrongAnswer3: '4' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What animal is known as the "King of the Jungle"?', correctAnswer: 'Lion', wrongAnswer1: 'Tiger', wrongAnswer2: 'Elephant', wrongAnswer3: 'Gorilla' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many degrees in a circle?', correctAnswer: '360', wrongAnswer1: '180', wrongAnswer2: '270', wrongAnswer3: '90' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the main ingredient in bread?', correctAnswer: 'Flour', wrongAnswer1: 'Sugar', wrongAnswer2: 'Milk', wrongAnswer3: 'Eggs' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many teeth does an adult human typically have?', correctAnswer: '32', wrongAnswer1: '28', wrongAnswer2: '30', wrongAnswer3: '36' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of Japan?', correctAnswer: 'Tokyo', wrongAnswer1: 'Osaka', wrongAnswer2: 'Kyoto', wrongAnswer3: 'Nagoya' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many zeros in one million?', correctAnswer: '6', wrongAnswer1: '5', wrongAnswer2: '7', wrongAnswer3: '8' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the largest land animal?', correctAnswer: 'African elephant', wrongAnswer1: 'Hippopotamus', wrongAnswer2: 'Rhinoceros', wrongAnswer3: 'Giraffe' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many seconds in a minute?', correctAnswer: '60', wrongAnswer1: '30', wrongAnswer2: '100', wrongAnswer3: '50' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What color are emeralds?', correctAnswer: 'Green', wrongAnswer1: 'Red', wrongAnswer2: 'Blue', wrongAnswer3: 'Yellow' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many players on a soccer team?', correctAnswer: '11', wrongAnswer1: '10', wrongAnswer2: '12', wrongAnswer3: '9' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of Germany?', correctAnswer: 'Berlin', wrongAnswer1: 'Munich', wrongAnswer2: 'Hamburg', wrongAnswer3: 'Frankfurt' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many keys on a standard piano?', correctAnswer: '88', wrongAnswer1: '76', wrongAnswer2: '96', wrongAnswer3: '64' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the largest internal organ in humans?', correctAnswer: 'Liver', wrongAnswer1: 'Brain', wrongAnswer2: 'Heart', wrongAnswer3: 'Lungs' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many rings in the Olympic symbol?', correctAnswer: '5', wrongAnswer1: '4', wrongAnswer2: '6', wrongAnswer3: '7' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the smallest country in the world?', correctAnswer: 'Vatican City', wrongAnswer1: 'Monaco', wrongAnswer2: 'Malta', wrongAnswer3: 'San Marino' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many seasons are there in a year?', correctAnswer: '4', wrongAnswer1: '3', wrongAnswer2: '5', wrongAnswer3: '6' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of Canada?', correctAnswer: 'Ottawa', wrongAnswer1: 'Toronto', wrongAnswer2: 'Vancouver', wrongAnswer3: 'Montreal' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many bones in the human body?', correctAnswer: '206', wrongAnswer1: '205', wrongAnswer2: '215', wrongAnswer3: '196' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the hardest natural substance?', correctAnswer: 'Diamond', wrongAnswer1: 'Quartz', wrongAnswer2: 'Steel', wrongAnswer3: 'Granite' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many cents in a dollar?', correctAnswer: '100', wrongAnswer1: '50', wrongAnswer2: '10', wrongAnswer3: '25' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of Australia?', correctAnswer: 'Canberra', wrongAnswer1: 'Sydney', wrongAnswer2: 'Melbourne', wrongAnswer3: 'Brisbane' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many days in February during a leap year?', correctAnswer: '29', wrongAnswer1: '28', wrongAnswer2: '30', wrongAnswer3: '31' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the fastest land animal?', correctAnswer: 'Cheetah', wrongAnswer1: 'Lion', wrongAnswer2: 'Leopard', wrongAnswer3: 'Horse' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many eyes does a typical person have?', correctAnswer: '2', wrongAnswer1: '1', wrongAnswer2: '3', wrongAnswer3: '4' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of Egypt?', correctAnswer: 'Cairo', wrongAnswer1: 'Alexandria', wrongAnswer2: 'Giza', wrongAnswer3: 'Luxor' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many minutes in an hour?', correctAnswer: '60', wrongAnswer1: '30', wrongAnswer2: '100', wrongAnswer3: '50' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the largest type of big cat?', correctAnswer: 'Tiger', wrongAnswer1: 'Lion', wrongAnswer2: 'Jaguar', wrongAnswer3: 'Leopard' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many letters in the English alphabet?', correctAnswer: '26', wrongAnswer1: '25', wrongAnswer2: '27', wrongAnswer3: '24' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of the United Kingdom?', correctAnswer: 'London', wrongAnswer1: 'Manchester', wrongAnswer2: 'Edinburgh', wrongAnswer3: 'Birmingham' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many sides does a pentagon have?', correctAnswer: '5', wrongAnswer1: '6', wrongAnswer2: '4', wrongAnswer3: '7' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the boiling point of water in Celsius?', correctAnswer: '100°C', wrongAnswer1: '0°C', wrongAnswer2: '50°C', wrongAnswer3: '212°C' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many wings does a butterfly have?', correctAnswer: '4', wrongAnswer1: '2', wrongAnswer2: '6', wrongAnswer3: '8' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the main language spoken in Brazil?', correctAnswer: 'Portuguese', wrongAnswer1: 'Spanish', wrongAnswer2: 'English', wrongAnswer3: 'French' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many years in a decade?', correctAnswer: '10', wrongAnswer1: '5', wrongAnswer2: '100', wrongAnswer3: '20' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the speed of light?', correctAnswer: '299,792 km/s', wrongAnswer1: '150,000 km/s', wrongAnswer2: '500,000 km/s', wrongAnswer3: '100,000 km/s' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many consonants in the English alphabet?', correctAnswer: '21', wrongAnswer1: '20', wrongAnswer2: '22', wrongAnswer3: '19' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of Russia?', correctAnswer: 'Moscow', wrongAnswer1: 'St. Petersburg', wrongAnswer2: 'Kyiv', wrongAnswer3: 'Minsk' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many chambers does the human heart have?', correctAnswer: '4', wrongAnswer1: '2', wrongAnswer2: '3', wrongAnswer3: '5' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What planet is known as the Red Planet?', correctAnswer: 'Mars', wrongAnswer1: 'Venus', wrongAnswer2: 'Jupiter', wrongAnswer3: 'Saturn' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many days in a non-leap year?', correctAnswer: '365', wrongAnswer1: '366', wrongAnswer2: '364', wrongAnswer3: '360' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the largest bird in the world?', correctAnswer: 'Ostrich', wrongAnswer1: 'Eagle', wrongAnswer2: 'Albatross', wrongAnswer3: 'Condor' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many inches in a foot?', correctAnswer: '12', wrongAnswer1: '10', wrongAnswer2: '6', wrongAnswer3: '8' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of China?', correctAnswer: 'Beijing', wrongAnswer1: 'Shanghai', wrongAnswer2: 'Hong Kong', wrongAnswer3: 'Guangzhou' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many tentacles does an octopus have?', correctAnswer: '8', wrongAnswer1: '6', wrongAnswer2: '10', wrongAnswer3: '12' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the symbol for gold?', correctAnswer: 'Au', wrongAnswer1: 'Ag', wrongAnswer2: 'Fe', wrongAnswer3: 'Gd' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many years in a century?', correctAnswer: '100', wrongAnswer1: '50', wrongAnswer2: '10', wrongAnswer3: '1000' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the largest continent?', correctAnswer: 'Asia', wrongAnswer1: 'Africa', wrongAnswer2: 'North America', wrongAnswer3: 'Europe' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many degrees in a right angle?', correctAnswer: '90', wrongAnswer1: '45', wrongAnswer2: '180', wrongAnswer3: '60' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of India?', correctAnswer: 'New Delhi', wrongAnswer1: 'Mumbai', wrongAnswer2: 'Bangalore', wrongAnswer3: 'Kolkata' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many pairs of ribs does a human have?', correctAnswer: '12', wrongAnswer1: '10', wrongAnswer2: '14', wrongAnswer3: '11' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the smallest ocean?', correctAnswer: 'Arctic', wrongAnswer1: 'Indian', wrongAnswer2: 'Southern', wrongAnswer3: 'Atlantic' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many hearts does an octopus have?', correctAnswer: '3', wrongAnswer1: '1', wrongAnswer2: '2', wrongAnswer3: '4' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of Mexico?', correctAnswer: 'Mexico City', wrongAnswer1: 'Guadalajara', wrongAnswer2: 'Monterrey', wrongAnswer3: 'Cancún' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many teeth does a shark have typically?', correctAnswer: '300', wrongAnswer1: '50', wrongAnswer2: '100', wrongAnswer3: '500' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the most spoken language in the world?', correctAnswer: 'Mandarin Chinese', wrongAnswer1: 'English', wrongAnswer2: 'Spanish', wrongAnswer3: 'Hindi' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'How many vowels in the English alphabet?', correctAnswer: '5', wrongAnswer1: '4', wrongAnswer2: '6', wrongAnswer3: '7' },
  { category: 'general_knowledge', difficulty: 'easy', questionText: 'What is the capital of South Korea?', correctAnswer: 'Seoul', wrongAnswer1: 'Busan', wrongAnswer2: 'Incheon', wrongAnswer3: 'Daegu' },

  // MEDIUM (80)
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the smallest bone in the human body?', correctAnswer: 'Stapes (in ear)', wrongAnswer1: 'Femur', wrongAnswer2: 'Fibula', wrongAnswer3: 'Radius' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What year did World War II end?', correctAnswer: '1945', wrongAnswer1: '1944', wrongAnswer2: '1946', wrongAnswer3: '1943' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many elements in the periodic table?', correctAnswer: '118', wrongAnswer1: '108', wrongAnswer2: '98', wrongAnswer3: '128' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the pH of pure water?', correctAnswer: '7', wrongAnswer1: '5', wrongAnswer2: '9', wrongAnswer3: '0' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who painted the Mona Lisa?', correctAnswer: 'Leonardo da Vinci', wrongAnswer1: 'Michelangelo', wrongAnswer2: 'Raphael', wrongAnswer3: 'Donatello' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the currency of Japan?', correctAnswer: 'Yen', wrongAnswer1: 'Yuan', wrongAnswer2: 'Won', wrongAnswer3: 'Ringgit' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many symphonies did Beethoven compose?', correctAnswer: '9', wrongAnswer1: '10', wrongAnswer2: '8', wrongAnswer3: '7' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the largest desert in the world?', correctAnswer: 'Antarctic Desert', wrongAnswer1: 'Sahara', wrongAnswer2: 'Arabian', wrongAnswer3: 'Gobi' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What year did the Titanic sink?', correctAnswer: '1912', wrongAnswer1: '1911', wrongAnswer2: '1913', wrongAnswer3: '1910' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many time zones does Russia span?', correctAnswer: '11', wrongAnswer1: '9', wrongAnswer2: '7', wrongAnswer3: '13' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the chemical symbol for silver?', correctAnswer: 'Ag', wrongAnswer1: 'Si', wrongAnswer2: 'Au', wrongAnswer3: 'Sv' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who wrote "Romeo and Juliet"?', correctAnswer: 'William Shakespeare', wrongAnswer1: 'Charles Dickens', wrongAnswer2: 'Jane Austen', wrongAnswer3: 'Mark Twain' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Thailand?', correctAnswer: 'Bangkok', wrongAnswer1: 'Phuket', wrongAnswer2: 'Chiang Mai', wrongAnswer3: 'Pattaya' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many strings does a violin have?', correctAnswer: '4', wrongAnswer1: '5', wrongAnswer2: '6', wrongAnswer3: '3' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the longest river in the world?', correctAnswer: 'Nile', wrongAnswer1: 'Amazon', wrongAnswer2: 'Yangtze', wrongAnswer3: 'Mississippi' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What year was the internet invented?', correctAnswer: '1983', wrongAnswer1: '1991', wrongAnswer2: '1975', wrongAnswer3: '1969' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many countries are in the United Nations?', correctAnswer: '193', wrongAnswer1: '190', wrongAnswer2: '195', wrongAnswer3: '200' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the smallest planet in our solar system?', correctAnswer: 'Mercury', wrongAnswer1: 'Mars', wrongAnswer2: 'Venus', wrongAnswer3: 'Pluto' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who invented the telephone?', correctAnswer: 'Alexander Graham Bell', wrongAnswer1: 'Thomas Edison', wrongAnswer2: 'Nikola Tesla', wrongAnswer3: 'Guglielmo Marconi' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Argentina?', correctAnswer: 'Buenos Aires', wrongAnswer1: 'Córdoba', wrongAnswer2: 'Rosario', wrongAnswer3: 'Mendoza' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many bones are in the human skull?', correctAnswer: '22', wrongAnswer1: '20', wrongAnswer2: '24', wrongAnswer3: '18' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the rarest blood type?', correctAnswer: 'AB negative', wrongAnswer1: 'O negative', wrongAnswer2: 'A negative', wrongAnswer3: 'B negative' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who discovered penicillin?', correctAnswer: 'Alexander Fleming', wrongAnswer1: 'Louis Pasteur', wrongAnswer2: 'Robert Koch', wrongAnswer3: 'Joseph Lister' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Portugal?', correctAnswer: 'Lisbon', wrongAnswer1: 'Porto', wrongAnswer2: 'Braga', wrongAnswer3: 'Coimbra' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many keys on a standard computer keyboard?', correctAnswer: '104', wrongAnswer1: '101', wrongAnswer2: '88', wrongAnswer3: '108' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the largest island in the Mediterranean?', correctAnswer: 'Sicily', wrongAnswer1: 'Sardinia', wrongAnswer2: 'Cyprus', wrongAnswer3: 'Crete' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who painted "The Starry Night"?', correctAnswer: 'Vincent van Gogh', wrongAnswer1: 'Claude Monet', wrongAnswer2: 'Pablo Picasso', wrongAnswer3: 'Paul Cézanne' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Switzerland?', correctAnswer: 'Bern', wrongAnswer1: 'Zurich', wrongAnswer2: 'Geneva', wrongAnswer3: 'Basel' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many teeth do adult cats have?', correctAnswer: '30', wrongAnswer1: '32', wrongAnswer2: '28', wrongAnswer3: '26' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the speed of sound in air?', correctAnswer: '343 m/s', wrongAnswer1: '300 m/s', wrongAnswer2: '400 m/s', wrongAnswer3: '500 m/s' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who wrote "1984"?', correctAnswer: 'George Orwell', wrongAnswer1: 'Aldous Huxley', wrongAnswer2: 'Ray Bradbury', wrongAnswer3: 'H.G. Wells' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Turkey?', correctAnswer: 'Ankara', wrongAnswer1: 'Istanbul', wrongAnswer2: 'Izmir', wrongAnswer3: 'Bursa' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many chromosomes do humans have?', correctAnswer: '46', wrongAnswer1: '44', wrongAnswer2: '48', wrongAnswer3: '42' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the tallest building in the world?', correctAnswer: 'Burj Khalifa', wrongAnswer1: 'Shanghai Tower', wrongAnswer2: 'Abraj Al-Bait', wrongAnswer3: 'Taipei 101' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who discovered gravity?', correctAnswer: 'Isaac Newton', wrongAnswer1: 'Galileo Galilei', wrongAnswer2: 'Albert Einstein', wrongAnswer3: 'Johannes Kepler' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Norway?', correctAnswer: 'Oslo', wrongAnswer1: 'Bergen', wrongAnswer2: 'Trondheim', wrongAnswer3: 'Stavanger' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many cards in a standard deck?', correctAnswer: '52', wrongAnswer1: '48', wrongAnswer2: '54', wrongAnswer3: '50' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the most abundant gas in Earth\'s atmosphere?', correctAnswer: 'Nitrogen', wrongAnswer1: 'Oxygen', wrongAnswer2: 'Carbon dioxide', wrongAnswer3: 'Argon' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who invented the light bulb?', correctAnswer: 'Thomas Edison', wrongAnswer1: 'Nikola Tesla', wrongAnswer2: 'Benjamin Franklin', wrongAnswer3: 'Alexander Bell' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Vietnam?', correctAnswer: 'Hanoi', wrongAnswer1: 'Ho Chi Minh City', wrongAnswer2: 'Da Nang', wrongAnswer3: 'Hue' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many faces does a cube have?', correctAnswer: '6', wrongAnswer1: '8', wrongAnswer2: '12', wrongAnswer3: '4' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the longest bone in the human body?', correctAnswer: 'Femur', wrongAnswer1: 'Tibia', wrongAnswer2: 'Humerus', wrongAnswer3: 'Radius' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who wrote "The Odyssey"?', correctAnswer: 'Homer', wrongAnswer1: 'Virgil', wrongAnswer2: 'Sophocles', wrongAnswer3: 'Euripides' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of New Zealand?', correctAnswer: 'Wellington', wrongAnswer1: 'Auckland', wrongAnswer2: 'Christchurch', wrongAnswer3: 'Hamilton' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many teeth do adult dogs have?', correctAnswer: '42', wrongAnswer1: '32', wrongAnswer2: '36', wrongAnswer3: '40' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the atomic number of carbon?', correctAnswer: '6', wrongAnswer1: '12', wrongAnswer2: '8', wrongAnswer3: '4' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who painted "The Last Supper"?', correctAnswer: 'Leonardo da Vinci', wrongAnswer1: 'Michelangelo', wrongAnswer2: 'Raphael', wrongAnswer3: 'Caravaggio' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Poland?', correctAnswer: 'Warsaw', wrongAnswer1: 'Krakow', wrongAnswer2: 'Gdansk', wrongAnswer3: 'Wroclaw' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many watts in a kilowatt?', correctAnswer: '1000', wrongAnswer1: '100', wrongAnswer2: '10000', wrongAnswer3: '500' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the largest volcano in the world?', correctAnswer: 'Mauna Loa', wrongAnswer1: 'Mount Vesuvius', wrongAnswer2: 'Mount Fuji', wrongAnswer3: 'Kilimanjaro' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who discovered the electron?', correctAnswer: 'J.J. Thomson', wrongAnswer1: 'Ernest Rutherford', wrongAnswer2: 'Niels Bohr', wrongAnswer3: 'Marie Curie' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Finland?', correctAnswer: 'Helsinki', wrongAnswer1: 'Turku', wrongAnswer2: 'Tampere', wrongAnswer3: 'Espoo' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many millimeters in a centimeter?', correctAnswer: '10', wrongAnswer1: '100', wrongAnswer2: '5', wrongAnswer3: '1' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the second most spoken language?', correctAnswer: 'Spanish', wrongAnswer1: 'English', wrongAnswer2: 'Hindi', wrongAnswer3: 'Arabic' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who wrote "Pride and Prejudice"?', correctAnswer: 'Jane Austen', wrongAnswer1: 'Charlotte Brontë', wrongAnswer2: 'Emily Brontë', wrongAnswer3: 'George Eliot' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Austria?', correctAnswer: 'Vienna', wrongAnswer1: 'Salzburg', wrongAnswer2: 'Graz', wrongAnswer3: 'Innsbruck' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many teeth do adult horses have?', correctAnswer: '40-44', wrongAnswer1: '30-36', wrongAnswer2: '50-54', wrongAnswer3: '20-24' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the most common element in the universe?', correctAnswer: 'Hydrogen', wrongAnswer1: 'Helium', wrongAnswer2: 'Oxygen', wrongAnswer3: 'Carbon' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who discovered radioactivity?', correctAnswer: 'Marie Curie', wrongAnswer1: 'Albert Einstein', wrongAnswer2: 'Niels Bohr', wrongAnswer3: 'Max Planck' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Ireland?', correctAnswer: 'Dublin', wrongAnswer1: 'Cork', wrongAnswer2: 'Galway', wrongAnswer3: 'Limerick' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many chambers in an insect heart?', correctAnswer: '1', wrongAnswer1: '2', wrongAnswer2: '4', wrongAnswer3: '0' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the melting point of iron?', correctAnswer: '1538°C', wrongAnswer1: '1000°C', wrongAnswer2: '2000°C', wrongAnswer3: '500°C' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who wrote "Hamlet"?', correctAnswer: 'William Shakespeare', wrongAnswer1: 'Christopher Marlowe', wrongAnswer2: 'Ben Jonson', wrongAnswer3: 'John Milton' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Belgium?', correctAnswer: 'Brussels', wrongAnswer1: 'Antwerp', wrongAnswer2: 'Bruges', wrongAnswer3: 'Ghent' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many moons does Mars have?', correctAnswer: '2', wrongAnswer1: '1', wrongAnswer2: '3', wrongAnswer3: '0' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the largest lake in the world?', correctAnswer: 'Caspian Sea', wrongAnswer1: 'Lake Superior', wrongAnswer2: 'Lake Victoria', wrongAnswer3: 'Lake Baikal' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who invented the printing press?', correctAnswer: 'Johannes Gutenberg', wrongAnswer1: 'Benjamin Franklin', wrongAnswer2: 'William Caxton', wrongAnswer3: 'Aldus Manutius' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Denmark?', correctAnswer: 'Copenhagen', wrongAnswer1: 'Aarhus', wrongAnswer2: 'Odense', wrongAnswer3: 'Aalborg' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many teeth does a great white shark have?', correctAnswer: '300', wrongAnswer1: '100', wrongAnswer2: '500', wrongAnswer3: '200' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the smallest country in Asia?', correctAnswer: 'Maldives', wrongAnswer1: 'Singapore', wrongAnswer2: 'Bahrain', wrongAnswer3: 'Brunei' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who discovered DNA structure?', correctAnswer: 'Watson and Crick', wrongAnswer1: 'Gregor Mendel', wrongAnswer2: 'Charles Darwin', wrongAnswer3: 'Louis Pasteur' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Czech Republic?', correctAnswer: 'Prague', wrongAnswer1: 'Brno', wrongAnswer2: 'Ostrava', wrongAnswer3: 'Pilsen' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'How many sides does a dodecagon have?', correctAnswer: '12', wrongAnswer1: '10', wrongAnswer2: '14', wrongAnswer3: '8' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the heaviest naturally occurring element?', correctAnswer: 'Uranium', wrongAnswer1: 'Lead', wrongAnswer2: 'Gold', wrongAnswer3: 'Plutonium' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'Who wrote "Moby Dick"?', correctAnswer: 'Herman Melville', wrongAnswer1: 'Mark Twain', wrongAnswer2: 'Edgar Allan Poe', wrongAnswer3: 'Nathaniel Hawthorne' },
  { category: 'general_knowledge', difficulty: 'medium', questionText: 'What is the capital of Greece?', correctAnswer: 'Athens', wrongAnswer1: 'Thessaloniki', wrongAnswer2: 'Patras', wrongAnswer3: 'Heraklion' },

  // HARD (40)
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the only mammal that can fly?', correctAnswer: 'Bat', wrongAnswer1: 'Flying squirrel', wrongAnswer2: 'Sugar glider', wrongAnswer3: 'Flying lemur' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the Mohs hardness of talc?', correctAnswer: '1', wrongAnswer1: '2', wrongAnswer2: '0', wrongAnswer3: '3' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'Who was the first person to reach the South Pole?', correctAnswer: 'Roald Amundsen', wrongAnswer1: 'Robert Scott', wrongAnswer2: 'Ernest Shackleton', wrongAnswer3: 'Richard Byrd' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the half-life of carbon-14?', correctAnswer: '5,730 years', wrongAnswer1: '50,000 years', wrongAnswer2: '1,000 years', wrongAnswer3: '10,000 years' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'Who wrote "The Divine Comedy"?', correctAnswer: 'Dante Alighieri', wrongAnswer1: 'Giovanni Boccaccio', wrongAnswer2: 'Petrarch', wrongAnswer3: 'Geoffrey Chaucer' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the square root of 441?', correctAnswer: '21', wrongAnswer1: '20', wrongAnswer2: '22', wrongAnswer3: '19' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'In what year was the Magna Carta signed?', correctAnswer: '1215', wrongAnswer1: '1066', wrongAnswer2: '1453', wrongAnswer3: '1492' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the atomic number of uranium?', correctAnswer: '92', wrongAnswer1: '82', wrongAnswer2: '102', wrongAnswer3: '88' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'Who discovered the neutron?', correctAnswer: 'James Chadwick', wrongAnswer1: 'Ernest Rutherford', wrongAnswer2: 'Niels Bohr', wrongAnswer3: 'J.J. Thomson' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the capital of Kazakhstan?', correctAnswer: 'Astana (Nur-Sultan)', wrongAnswer1: 'Almaty', wrongAnswer2: 'Shymkent', wrongAnswer3: 'Aktobe' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'How many bones are in a giraffe\'s neck?', correctAnswer: '7', wrongAnswer1: '14', wrongAnswer2: '21', wrongAnswer3: '10' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is Avogadro\'s number?', correctAnswer: '6.022 x 10²³', wrongAnswer1: '3.14 x 10²³', wrongAnswer2: '9.81 x 10²³', wrongAnswer3: '1.602 x 10²³' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'Who composed "The Four Seasons"?', correctAnswer: 'Antonio Vivaldi', wrongAnswer1: 'Johann Bach', wrongAnswer2: 'Wolfgang Mozart', wrongAnswer3: 'Ludwig Beethoven' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the capital of Uzbekistan?', correctAnswer: 'Tashkent', wrongAnswer1: 'Samarkand', wrongAnswer2: 'Bukhara', wrongAnswer3: 'Khiva' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'How many bytes in a kilobyte?', correctAnswer: '1024', wrongAnswer1: '1000', wrongAnswer2: '512', wrongAnswer3: '2048' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the densest naturally occurring element?', correctAnswer: 'Osmium', wrongAnswer1: 'Platinum', wrongAnswer2: 'Iridium', wrongAnswer3: 'Gold' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'Who painted "The Birth of Venus"?', correctAnswer: 'Sandro Botticelli', wrongAnswer1: 'Raphael', wrongAnswer2: 'Titian', wrongAnswer3: 'Caravaggio' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the capital of Mongolia?', correctAnswer: 'Ulaanbaatar', wrongAnswer1: 'Erdenet', wrongAnswer2: 'Darkhan', wrongAnswer3: 'Choibalsan' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'How many ribs does a sloth have?', correctAnswer: '24', wrongAnswer1: '12', wrongAnswer2: '18', wrongAnswer3: '20' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is Planck\'s constant?', correctAnswer: '6.626 x 10⁻³⁴ J⋅s', wrongAnswer1: '3.14 x 10⁻³⁴ J⋅s', wrongAnswer2: '9.81 x 10⁻³⁴ J⋅s', wrongAnswer3: '1.6 x 10⁻³⁴ J⋅s' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'Who wrote "Paradise Lost"?', correctAnswer: 'John Milton', wrongAnswer1: 'William Blake', wrongAnswer2: 'John Donne', wrongAnswer3: 'Edmund Spenser' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the capital of Azerbaijan?', correctAnswer: 'Baku', wrongAnswer1: 'Ganja', wrongAnswer2: 'Sumqayit', wrongAnswer3: 'Lankaran' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'How many chambers in a crocodile heart?', correctAnswer: '4', wrongAnswer1: '2', wrongAnswer2: '3', wrongAnswer3: '5' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the speed of light in a vacuum (exact)?', correctAnswer: '299,792,458 m/s', wrongAnswer1: '300,000,000 m/s', wrongAnswer2: '299,000,000 m/s', wrongAnswer3: '298,792,458 m/s' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'Who discovered the neutron star?', correctAnswer: 'Jocelyn Bell Burnell', wrongAnswer1: 'Stephen Hawking', wrongAnswer2: 'Carl Sagan', wrongAnswer3: 'Fred Hoyle' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the capital of Kyrgyzstan?', correctAnswer: 'Bishkek', wrongAnswer1: 'Osh', wrongAnswer2: 'Jalal-Abad', wrongAnswer3: 'Karakol' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'How many degrees of freedom does a diatomic molecule have?', correctAnswer: '5', wrongAnswer1: '3', wrongAnswer2: '6', wrongAnswer3: '7' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the smallest unit of life?', correctAnswer: 'Cell', wrongAnswer1: 'Molecule', wrongAnswer2: 'Organelle', wrongAnswer3: 'Atom' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'Who composed "Requiem in D minor"?', correctAnswer: 'Wolfgang Amadeus Mozart', wrongAnswer1: 'Ludwig van Beethoven', wrongAnswer2: 'Franz Schubert', wrongAnswer3: 'Johannes Brahms' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the capital of Tajikistan?', correctAnswer: 'Dushanbe', wrongAnswer1: 'Khujand', wrongAnswer2: 'Kulob', wrongAnswer3: 'Qurghonteppa' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'How many fundamental forces in nature?', correctAnswer: '4', wrongAnswer1: '3', wrongAnswer2: '5', wrongAnswer3: '2' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the triple point of water?', correctAnswer: '0.01°C, 611.657 Pa', wrongAnswer1: '0°C, 1 atm', wrongAnswer2: '100°C, 1 atm', wrongAnswer3: '4°C, 1 atm' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'Who discovered the electron microscope?', correctAnswer: 'Ernst Ruska', wrongAnswer1: 'Anton van Leeuwenhoek', wrongAnswer2: 'Robert Hooke', wrongAnswer3: 'Carl Zeiss' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the capital of Turkmenistan?', correctAnswer: 'Ashgabat', wrongAnswer1: 'Turkmenbashi', wrongAnswer2: 'Mary', wrongAnswer3: 'Balkanabat' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'How many quarks in a proton?', correctAnswer: '3', wrongAnswer1: '2', wrongAnswer2: '4', wrongAnswer3: '6' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the Schwarzschild radius of the Sun?', correctAnswer: '3 km', wrongAnswer1: '1 km', wrongAnswer2: '10 km', wrongAnswer3: '30 km' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'Who wrote "The Canterbury Tales"?', correctAnswer: 'Geoffrey Chaucer', wrongAnswer1: 'William Langland', wrongAnswer2: 'Thomas Malory', wrongAnswer3: 'John Gower' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the capital of Bhutan?', correctAnswer: 'Thimphu', wrongAnswer1: 'Paro', wrongAnswer2: 'Punakha', wrongAnswer3: 'Phuentsholing' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'How many electrons can the 3d orbital hold?', correctAnswer: '10', wrongAnswer1: '6', wrongAnswer2: '8', wrongAnswer3: '14' },
  { category: 'general_knowledge', difficulty: 'hard', questionText: 'What is the Rydberg constant?', correctAnswer: '1.097 x 10⁷ m⁻¹', wrongAnswer1: '2.18 x 10⁷ m⁻¹', wrongAnswer2: '3.14 x 10⁷ m⁻¹', wrongAnswer3: '9.81 x 10⁷ m⁻¹' },
];

/**
 * Export complete question set
 * This file will be extended to include 1000 questions total
 * TODO: Add Geography (200), Science (200), Pop Culture (200), Sports (200)
 */
export const ALL_QUESTIONS = GENERAL_KNOWLEDGE_QUESTIONS;

console.log(`Total questions generated: ${ALL_QUESTIONS.length}`);
console.log('Note: This is a partial implementation. Full 1000 questions will be generated using AI assistance.');
